---
- name: Check if Docker is installed on the host
  command: docker version
  register: _docker_result
  failed_when: false
  changed_when: false

- name: Install Docker
  block:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 0EBFCD88
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: docker
        state: present

    - name: Update repositories cache and install 'docker-ce' package to latest version # noqa 403
      apt:
        name: "docker-ce"
        update_cache: yes
        state: latest

    - name: Add remote user to 'docker' group
      user:
        name: "{{ ansible_user }}"
        append: yes
        groups: docker
        state: present

    - name: Enable 'docker' service
      systemd:
        name: docker
        state: started
        enabled: yes
  when:
    - _docker_result.rc == 2
