---
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Install base dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - dnsutils
    - jq
    - unzip

- name: Disable Ubuntu motd-news
  lineinfile:
    dest: /etc/default/motd-news
    state: present
    regexp: '^ENABLED='
    line: 'ENABLED=0'

- name: Disable Firewall service
  become: true
  systemd:
    name: ufw
    state: stopped
    enabled: no

